name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and test archetype
        run: ./mvnw clean verify

      - uses: actions/upload-artifact@v2
        with:
          name: bonita-connector-pdf-stamp-latest.zip
          path: target/bonita-connector-pdf-stamp-*.zip
